---
title: "3주차 실습 3-1"
author: "Jiwon Kim"
date: '`r Sys.Date()`'
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## 1. 상관분석 (Correlation Analysis)
$$ 
\left\{
    \begin{array}{l}
      H_0 : 두 양적 자료 간의 상관관계가 없다. ({\rho}_{AB} = 0) \\
      H_1 : 두 양적 자료 간의 상관관계가 있다. ({\rho}_{AB} \neq 0)
    \end{array}
  \right.
$$

```{r}
#install.packages("tidyverse")
library(tidyverse)

str(cars)

cor <- cor.test(cars$dist, cars$speed, method = "pearson")

```

$$
T^{*} = \frac{r- \rho}{\sqrt \frac {1-{r}^{2}}{n-2}} \sim  t(n-2) ,  under H_0
$$
```{r}
# 검정통계량 t확인
(cor$estimate-0)/sqrt((1-cor$estimate^2)/cor$parameter)

#산점도 
plot(cars$dist ~ cars$speed, col = "red")

k <- lm(cars$dist ~ cars$speed)
abline(k) 

```


## 2. 회귀분석 (Regression Analysis)
    1) 단순 선형 회귀분석 (독립변수와 종속변수 1개)
     - 회귀모형식 추정 : 최소제곱법(Least Square Method) 
$$
Y_{i} = \beta_0 + \beta_1 X_i + \epsilon_i , i = 1,2,..,n 
$$

     - 회귀모형의 타당성 검정
$$ 
\left\{
    \begin{array}{l}
      H_0 : 회귀모형은 타당하지 않다.(추정된 회귀모형식은 유의하지 않다) \\
      H_1 : 회귀모형은 타당하다.(추정된 회귀모형식은 유의하다)
    \end{array}
  \right.
$$

     - 회귀계수의 유의성 검정
$$ 
\left\{
    \begin{array}{l}
      H_0 : \beta_1 = 0 (독립변수는 유의한 영향을 주지 않는다) \\
      H_1 : \beta_1 \neq 0 (독립변수는 유의한 영향을 준다)
    \end{array}
  \right.
$$

$$ 
\left\{
    \begin{array}{l}
      H_0 : \beta_0 = 0 (독립변수는 유이한 영향을 주지 않는다) \\
      H_1 : \beta_0 \neq 0 (독립변수는 유의한 영향을 준다)
    \end{array}
  \right.
$$

```{r}
res1 <- lm(formula = dist ~ speed, data = cars)
summary(res1)

#분산분석표 확인
summary.aov(res1)

SSR <- 21185
SST <- 21185 + 11354

R2 <- SSR / SST
R2  #전체변화량 중 회귀모형에 의해 설명되는 변화량

predict(res1, newdata = data.frame(speed = 100))
predict(res1, newdata = data.frame(speed = 100),
        interval = "confidence", level = 0.95)

```

    - 오차의 가정에 대해서 검정 (= 잔차분석)
```{r}
#선형성, 정규성, 등분산성, 독립성

par(mfrow=c(2,2))

plot(res1)

```
    

$$

\left\{
    \begin{array}{l}
      H_0 : 정규분포를 따른다./독립이다./등분산이다. \\
      H_1 : 정규분포를 따르지 않는다./독립이 아니다./이분산이다.
      \end{array}
  \right.
$$

```{r}
#정규성 검정
shapiro.test(res1$residuals)  

#독립성 검정
car::durbinWatsonTest(res1)   

#등분산성 검정
car::ncvTest(res1)

#독립성을 제외한 나머지 가정
#install.packages("gvlma")
library(gvlma)
gvlma::gvlma(res1)

```


    2) 다중 선형 회귀분석 
```{r}
data(iris)

str(iris)
iris2 <- iris[, -5]

fit1 <- lm(Sepal.Length ~ ., data = iris2)
summary(fit1)

predict(fit1, newdata = data.frame(Sepal.Width = 10,
                                   Petal.Length = 6,
                                   Petal.Width = 4))
                                
#잔차분석 생략
            
```

    2-1) 더미변수 (Dummy Variables, 가변수)
```{r}
head(iris)

iris %>% 
 dplyr::mutate(Species_d1 = ifelse(Species == "versicolor", 1, 0),
               Species_d2 = ifelse(Species == "virginica", 1, 0)) %>% 
 dplyr::select(-Species) -> iris3

View(iris3)

fit2 <- lm(formula = Sepal.Length ~ ., data = iris3)
summary(fit2) 

```

    2-2) 다중공선성과 변수 선택법
    
      (1) 모든 가능한 회귀 접근법(All possible regression approachs)
       -  2^p - 1 (p : X의 개수)
```{r}
head(attitude)
str(attitude)

full.model <- lm(formula = rating ~ ., data = attitude)

#install.packages("leaps")
library(leaps)

all_model <- leaps::regsubsets(x = rating ~ ., data = attitude)
summary(all_model)

summary(all_model)$rsq
summary(all_model)$cp
summary(all_model)$bic

```

    (2) 전진선택법(Forward Selection)
```{r}
start.lm <- lm(rating ~ 1, data = attitude)

forward_model <- step(start.lm, direction = "forward")
summary(forward_model)

```
    
    (3) 후진제거법(Backward Elimination) 
```{r}
backward_model <- step(full.lm, direction = "backward")
summary(backward_model)

```
    
    (4) 단계선택법(Stepwise)
```{r}
both_model <- step(start.lm, scope = list(upper=full.glm), direction = "both")
summary(both_model)

```

    (5) 다중공선성 확인 (VIF, 분산팽창요인)
```{r}
car::vif(fit1)

#VIF_1~3 확인
vif1 <- summary(lm(Sepal.Width ~ Petal.Length + Petal.Width, data = iris2))
vif1$r.squared <- 1/(1-vif1$r.squared^2)  

vif2 <- summary(lm(Petal.Length ~ Sepal.Width + Petal.Width, data = iris2))
vif2$r.squared <- 1/(1-vif2$r.squared^2)

vif3 <- summary(lm(Petal.Width ~ Sepal.Width + Petal.Length, data = iris2))
vif3$r.squared <- 1/(1-vif3$r.squared^2)

```

