---
title: "Untitled"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)

```

## vector


```{r cars}
vec1 <- c(1,2,3,4)
vec2 <- c("a","b","c","d")
vec3 <- c(F,T,T,T)
```

## vector, df, matrix

```{r pressure, echo=FALSE}
data.frame(vec1,vec2)
data.frame(c(vec1,vec2))

```

## factor

```{r}
set.seed(0709)
v <- sample(c("A","B","C"),5,T)
v

v2 <- factor(v)
v2
str(v2)


```

##names_성씨

```{r names}
#getwd()
name <- read.table("names.txt",header = T) %>%
  `colnames<-`("name")

t1 <- round(prop.table(table(name$name)),5)

f <- sort(t1,decreasing = T)[1:10]
l <- sort(t1,T)[-(1:10)]

df.name <- data.frame(
   성씨 = c(names(f),"기타")
  ,비율 = c(f,sum(l))
  ,row.names = 1:11
)

pie(
   df.name$비율
  ,clockwise = T
  ,labels = paste( df.name$성씨
                  ,"\n"
                  ,df.name$비율)
  ,cex=1
  )


```


##윷놀이

```{r}

yut <- function(n){
  play <- replicate(n,rbinom(4,1,0.6))
  res <- colSums(play)
  res <- factor(res, levels = c(1:4,0))
  t <- table(res)/n
  print(t)
  pie(t
      ,clockwise = T
      ,labels = paste0(
         c("도","개","걸","윷","모")
        ,"\n"
        ,"(",t,")")
      ,cex=0.8)
}
yut(100000)

```

##coin

```{r}

coin <- function(n){
  play <- replicate(n,rbinom(1,1,0.5)) #replicate(n,sample(0:1,1))
  res <- table(play)
  res1 <- prop.table(res)
  print(res1)
  pie(res1
      ,clockwise = T
      ,labels = paste0(
         c("앞면","뒷면")
        ,"\n"
        ,"(",res1,")")
      ,cex=0.8)
}

coin(1000)

```



